name: red-deploy
namespace: skills
labels: app
containers:
  name: red-containers
  image: 003150130236.dkr.ecr.ap-northeast-2.amazonaws.com/skills-red-repo:v1.0.0
env:
  passwd: DB_PASSWD
  user: DB_USER
  url: DB_URL
  secretkey: skills-secrets
